### ISSUE TITLE
Self Hosting Guide

### ISSUE THREAD

**Issue by karimawi** [addyett/readme-now-playing#4]
Hey, I'm very sorry to see how Spotify butchered this project with their API limitations, I really love how this looks, I want to use it, so if you could add a self-hosting guide, a .env example and a Vervel deploy button, that'd be awesome because I don't have much experience when it comes to web, I mainly write Python and C# and I feel like a lot of people would find that useful, thanks 😊

**Comment by totallynotadi** [comment]
Spotify didn't approve the quota extension request that would allow users to authorize this app to access required data for providing them with the cards, I'll give it another shot making a request for the same the second time.

glad that everyone liked the cards, definitely doing a self hosting guide soon, thanks so much :)

**Comment by karimawi** [comment]
Thanks for the response, I do think those requests depend on nothing but sheer luck, and the amount of bandwidth they can currently afford, I don't think your application is the sole reason of rejection, because similar applications have gotten quota extensions before so, good luck on your second time, maybe this time they'll accept, and looking forward to add this to my readme 😄 .

**Comment by rajatcj** [comment]
Waiting for the selfhost guide~ Hope its ready soon

**Comment by zudsniper** [comment]
Would love a self-hosting guide, as has been expressed here. Bump!
