### ISSUE TITLE
Its broken

### ISSUE THREAD

**Issue by WarFiN123** [addyett/readme-now-playing#8]
![image](https://github.com/user-attachments/assets/b7a7bb32-0d89-45b8-839f-864c7dc5395e)

**Comment by dibenzepin** [comment]
from #6:

> The problem is that something, not sure whether it's the Spotify API or the normal Vercel deploy. tries to redirect to the old application (which doesn't exist anymore, hence the Not Found message)
> 
> On the page that shows this error, change the link from `https://readme-now-playing.vercel.app/callback/q?...` to `https://now-playing-cards.vercel.app/callback/q?...` and then it should spit out your User ID right
> 
> It still doesn't work after that tho...there's an internal server error returned

the [self-hosting doc](https://github.com/totallynotadi/now-playing-cards/blob/main/DEPLOYING.md) might help, if you're up for it
